"""Creacion inicial de tablas

Revision ID: a01f33d744bd
Revises: 
Create Date: 2026-06-25 19:02:50.549793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a01f33d744bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre_cuenta', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('tipo_cuenta', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familias',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nombre_familia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_familias_nombre_familia'), 'familias', ['nombre_familia'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre_categoria', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('presupuesto_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('icono', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('familia_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('CARGO', 'ABONO', 'TRANSFERENCIA', name='tipomovimiento'), nullable=False),
    sa.Column('categoria_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuenta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuenta_destino_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_de_cambio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['cuenta_destino_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_fecha'), 'transacciones', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacciones_fecha'), table_name='transacciones')
    op.drop_table('transacciones')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_familias_nombre_familia'), table_name='familias')
    op.drop_table('familias')
    op.drop_table('cuentas')
    # ### end Alembic commands ###
